version: '3'
 
services:
  db:
    image: mysql:latest
    container_name: userbook_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: userbook_db
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: userbook_phpmac
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
volumes:
  dbdata: